# Generated by Django 3.0.2 on 2020-01-14 03:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('page', '0002_auto_20200113_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
