# Generated by Django 3.0.2 on 2020-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200114_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(help_text='A brief descripton of item. eg. electronics, letter, etc'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_pin',
            field=models.CharField(help_text='A unique pin in the form of password', max_length=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='tracking_number',
            field=models.CharField(help_text='A 12 digit Unique number', max_length=12),
        ),
    ]
