# Generated by Django 3.0.2 on 2020-01-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20200115_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=13)),
            ],
        ),
    ]
