# Generated by Django 3.0.2 on 2020-01-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='enquiry',
            field=models.TextField(help_text='Includes comments', max_length=1000, null=True),
        ),
    ]
