# Generated by Django 3.0.2 on 2020-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20200120_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='item',
            name='route',
        ),
        migrations.AddField(
            model_name='item',
            name='service',
            field=models.CharField(help_text='Please state fleet service type item is registered for', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(help_text='Please enter the weight of item', max_length=10, null=True),
        ),
    ]
