# Generated by Django 3.0.2 on 2020-01-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Current Country or region of item', max_length=100)),
                ('activity', models.TextField(help_text='Whats happening to item at current region')),
            ],
        ),
    ]
