# Generated by Django 3.0.2 on 2020-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transit',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='transit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='destination',
            field=models.CharField(blank=True, help_text='Where item is been delivered', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='pickup',
            field=models.CharField(blank=True, help_text='Item was picked up from', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='route',
            field=models.IntegerField(choices=[(1, 'Air'), (2, 'Sea'), (3, 'Land')], help_text='How is item been transported', null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
