# Generated by Django 3.0.2 on 2020-01-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200122_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transit',
            options={},
        ),
    ]
